cmake_minimum_required(VERSION 3.2)
project(RUVMBlender)
add_library(RUVMBlender SHARED Src/RuvmBlender.c)
if (UNIX)
	set(CMAKE_C_FLAGS "-D PLATFORM_LINUX")
	set(RELEASE_FLAGS "-ftree-vectorize -mavx2 -finline-functions -flto -O2 -pthread -D PLATFORM_LINUX -fPIC")
	set(DEBUG_FLAGS "-g -O0 -DEBUG -pthread -Wshadow -Wunused -Wunused-parameter -D PLATFORM_LINUX -fPIC")
	if (APPLE)
		set(RUVM_LIB_PATH ../RUVM/build/macosShared)
	else()
		
		set(RUVM_LIB_PATH ../RUVM/Build/Debug)
	endif()
	if (NOT CMAKE_BUILD_TYPE)
		message("No build type specified, building release")
		set(CMAKE_BUILD_TYPE "RELEASE")
		set(CMAKE_C_FLAGS_RELEASE ${RELEASE_C_FLAGS})
		message("Build type is " + CMAKE_BUILD_TYPE)
	endif()
	if(CMAKE_BUILD_TYPE MATCHES DEBUG)
		message("Debug build -- using gcc")
		set(CMAKE_C_FLAGS ${DEBUG_FLAGS})
	endif(CMAKE_BUILD_TYPE MATCHES DEBUG)
	if(CMAKE_BUILD_TYPE MATCHES RELEASE)
		set(CMAKE_C_COMPILER clang)
		set(CMAKE_C_FLAGS_RELEASE ${RELEASE_FLAGS})
	endif(CMAKE_BUILD_TYPE MATCHES RELEASE)
endif()
if (WIN32)
	message("Building for Windows")
	set(CMAKE_C_FLAGS "/D PLATFORM_WINDOWS")
	set(CMAKE_C_STANDARD 11)
	set(RUVM_LIB_PATH ../RUVM/Build/Win/Release)
	set(ZLIB_LIBRARIES ${ZLIB_LIB_PATH})
	set(ZLIB_DEPENDENCIES )
	target_link_libraries(RUVMBlender PRIVATE ${ZLIB_LIBRARIES} ${ZLIB_DEPENDENCIES})
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
target_include_directories(RUVMBlender PUBLIC Src)
find_library(RUVMLIB RUVM PATHS ${RUVM_LIB_PATH})
target_link_libraries(RUVMBlender PRIVATE ${RUVMLIB})
set(RUVMLIB_INCLUDE_DIRS ../RUVM/Include)
target_include_directories(RUVMBlender PRIVATE ${RUVMLIB_INCLUDE_DIRS})
