# SPDX-FileCopyrightText: 2025 Caleb Dawson
# SPDX-License-Identifier: GPL-3.0-only

cmake_minimum_required(VERSION 3.5)
cmake_policy(SET CMP0091 NEW)
project(UvStuccoBlender)
add_library(UvStuccoBlender SHARED src/uv_stucco_blender.c)
option(FIND_ZLIB "Try to find zlib" ON)
option(FIND_ZLIB_CONAN "Use conan to find zlib" OFF)
option(ZLIB_INCLUDE "Include directory for zlib" "")
option(ZLIB_LIB "Lib directory for zlib" "")
if (NOT FIND_ZLIB)
	if (NOT ZLIB_INCLUDE OR NOT ZLIB_LIB)
		message(FATAL_ERROR "FIND_ZLIB disabled, specify dir with ZLIB_LIB & ZLIB_INCLUDE")
	endif()
endif()
get_property(IS_MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if (NOT IS_MULTI_CONFIG)
	message("Building for single build type")
	if (NOT CMAKE_BUILD_TYPE)
		message("No build type specified, building Release")
		set(CMAKE_BUILD_TYPE RELEASE "" FORCE)
	endif()
endif()
if (UNIX)
	message("Building for Unix")
	if(CMAKE_BUILD_TYPE MATCHES DEBUG)
		message("Building debug")
		set(CMAKE_C_FLAGS  "-g -O0 -DEBUG -pthread -Wshadow -Wunused -Wunused-parameter -D PLATFORM_LINUX -fPIC")
	endif()
	if(CMAKE_BUILD_TYPE MATCHES RELEASE)
		message("Building release")
		set(CMAKE_C_FLAGS "-ftree-vectorize -mavx2 -finline-functions -O2 -pthread -D PLATFORM_LINUX -fPIC")
	endif()
endif()
if (WIN32)
	message("Building for Windows")
	set(CMAKE_C_FLAGS "/D PLATFORM_WINDOWS /D WIN32 /D WINDOWS")
	set(CMAKE_C_STANDARD 11)
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
target_include_directories(UvStuccoBlender PUBLIC src)

target_include_directories(UvStuccoBlender PRIVATE extern/uv-stucco/include)
add_subdirectory(extern/uv-stucco)

message("FIND_ZLIB is " + ${FIND_ZLIB})
if (FIND_ZLIB)
	message("Attempting to find zlib")
	find_package(ZLIB REQUIRED)
	message("--zlib include is " + ${ZLIB_INCLUDE_DIRS})
	message("Note that if the above are mismatched, there may be errors at compile time.")
	message ("Consider disabling FIND_ZLIB and specifying manually using ZLIB_LIB and ZLIB_INCLUDE. Or using Conan.")
	message("See github docs for more info.")
	target_include_directories(UvStuccoBlender PRIVATE ${ZLIB_INCLUDE_DIRS})
	target_link_libraries(UvStuccoBlender ${ZLIB_LIBRARIES} ${ZLIB_DEPENDENCIES} UvStucco)
else()
	target_include_directories(UvStuccoBlender PRIVATE ${ZLIB_INCLUDE})
	target_link_libraries(UvStuccoBlender ${ZLIB_LIB} UvStucco)
endif()
