cmake_minimum_required(VERSION 3.2)
project(RUVMBlender)
if(CMAKE_BUILD_TYPE MATCHES DEBUG)
	message("Debug build -- using gcc")
	set(CMAKE_C_COMPILER gcc)
	set(CMAKE_C_FLAGS "-g -O0 -DEBUG -pthread -Wshadow -Wunused -Wunused-parameter -D PLATFORM_LINUX -fPIC")
endif(CMAKE_BUILD_TYPE MATCHES DEBUG)
if(CMAKE_BUILD_TYPE MATCHES RELEASE)
	message("Release build -- using clang")
	set(CMAKE_C_COMPILER clang)
	set(CMAKE_C_FLAGS_RELEASE "-ftree-vectorize -mavx2 -finline-functions -flto -O2 -pthread -D PLATFORM_LINUX -fPIC")
endif(CMAKE_BUILD_TYPE MATCHES RELEASE)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_library(RUVMBlender SHARED Src/RuvmBlender.c)
target_include_directories(RUVMBlender PUBLIC Src)
find_library(RUVMLIB RUVM PATHS ../RUVM/Build/Debug)
target_link_libraries(RUVMBlender PRIVATE ${RUVMLIB})
set(RUVMLIB_INCLUDE_DIRS ../RUVM/Include)
target_include_directories(RUVMBlender PRIVATE ${RUVMLIB_INCLUDE_DIRS})
